Support alternative gemm implementation sandboxes.
Detail:
- configure:
  - add support for --enable-sandbox=NAME to configure script, where NAME
    is a subdirectory of a new 'sandbox' directory that contains an
    alternative implementation of gemm. (For now, only implementations of
    gemm may be provided via a sandbox.);
  - add support for C++ compiler. C++ compilers are handled in a manner
    similar to that of C compilers, in that a default search order is
    used, and that CXX is searched for first, if the variable is set. In
    practice, the C++ compiler that is selected should correspond to the
    selected C compiler. (Example: If gcc is selected for C, g++ should
    be selected for C++.) The result of the search is output to config.mk
    via build/config.mk.in. NOTE: The use of C++ in BLIS is still
    hypothetical, but may eventually move to being experimental. This
    support was intended only for use of C++ within a gemm sandbox.
- build/config.mk.in:
  - define SANDBOX variable containing sandbox subdirectory name.
- build/bli_config.in:
  - define either of the BLIS_ENABLE_SANDBOX or BLIS_DISABLE_SANDBOX
    macros in bli_config.h.
- common.mk:
  - include makefile fragments that were propagated into the specified
    sandbox subdirectory;
  - generate different CFLAGS for sandboxes, as well as a separate
    CXXFLAGS variable for sandboxes when C++ source files are compiled;
  - isolate into a single location lists of file suffixes for various
    purposes.
  - reorganized/clean up code related to identifying header files and
    paths.
- Makefile:
  - generate object filepaths for and compile source code files found in
    sandbox sub-directory;
  - remove makefile fragments placed in sandbox sub-directory (cleanmk);
  - various other cleanups.
- Added .cc, .cpp, and .cxx to list of suffixes of files to recognize in
  makefile fragments (via build/gen-make-frags/suffix_list).
- Updated blis.h to conditionally #include bli_sandbox.h (via a new file,
  bli_sbox.h), which each sandbox is assumed to use for any type
  definitions and function prototypes it wishes to export out to blis.h.
- Conditionally disable bli_gemmnat() implementation in frame/3 when
  BLIS_ENABLE_SANDBOX is defined.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -83,8 +83,8 @@ print_usage()
 	echo "                 The path to which make will install libraries. If given,"
 	echo "                 LIBDIR will override the corresponding directory implied"
 	echo "                 by --prefix; if not not given, LIBDIR defaults to"
-	echo "                 PREFIX/lib. If LIBDIR refers to a directory that does not"
-	echo "                 exist, it will be created."
+	echo "                 PREFIX/lib. If LIBDIR refers to a directory that does"
+	echo "                 not exist, it will be created."
 	echo " "
 	echo "   --includedir=INCDIR"
 	echo " "
@@ -167,6 +167,16 @@ print_usage()
 	echo "                 Enable (disabled by default) building the CBLAS"
 	echo "                 compatibility layer. This automatically enables the"
 	echo "                 BLAS compatibility layer as well."
+	echo " "
+	echo "   -s NAME --enable-sandbox=NAME"
+	echo " "
+	echo "                 Enable a separate sandbox implementation of gemm. This"
+	echo "                 option disables BLIS's conventional gemm implementation"
+	echo "                 (which shares common infrastructure with other level-3"
+	echo "                 operations) and instead compiles and uses the code in"
+	echo "                 the NAME directory, which is expected to be a sub-"
+	echo "                 directory of 'sandbox'. By default, no sandboxes are"
+	echo "                 enabled."
 	echo " "
 	echo "   --with-memkind, --without-memkind"
 	echo " "
@@ -802,6 +812,23 @@ get_cc_search_list()
 	echo "${list}"
 }
 
+get_cxx_search_list()
+{
+	local list
+
+	# For Linux, Darwin (OS X), and generic OSes, prioritize g++.
+	list="g++ clang++ c++"
+
+	# For OpenBSD and FreeBSD, prioritize cc and clang over gcc.
+	if   [ "${os_name}" = "OpenBSD" ]; then
+		list="c++ clang++ g++"
+	elif [ "${os_name}" = "FreeBSD" ]; then
+		list="c++ clang++ g++"
+	fi
+
+	echo "${list}"
+}
+
 select_cc()
 {
 	local search_list se_suf the_cc cc rval
@@ -825,7 +852,47 @@ select_cc()
 	# works.
 	for cc in ${search_list}; do
 
-		# See if CC works and/or is present.
+		# See if the compiler works and/or is present.
+		rval=$(${cc} --version 2> ${se_file})
+
+		# If the output file is non-empty, we will use this compiler.
+		if [ -z "$(cat ${se_file})" ]; then
+			the_cc=${cc}
+			rm ${se_file}
+			break
+		else
+			rm ${se_file}
+		fi
+	done
+
+	# Return the selected compiler.
+	echo "${the_cc}"
+}
+
+select_cxx()
+{
+	local search_list se_suf the_cc cc rval
+
+	# This is the list of compilers to search for, and the order in which
+	# to search for them.
+	search_list=$1
+
+	se_file="cc_stderr.txt"
+
+	# If CXX contains something, add it to the beginning of our default
+	# search list.
+	if [ -n "${CXX}" ]; then
+		search_list="${CXX} ${search_order}"
+	fi
+
+	# Initialize our selected compiler to empty.
+	the_cc=""
+
+	# Try each compiler in the list and select the first one we find that
+	# works.
+	for cc in ${search_list}; do
+
+		# See if the compiler works and/or is present.
 		rval=$(${cc} --version 2> ${se_file})
 
 		# If the output file is non-empty, we will use this compiler.
@@ -1382,6 +1449,8 @@ main()
 	#declare -A kernel_registry
 	#declare -A kconfig_registry
 
+	# -- Basic names and paths --
+
 	# The name of the script, stripped of any preceeding path.
 	script_name=${0##*/}
 
@@ -1445,6 +1514,10 @@ main()
 	frame_dir='frame'
 	frame_dirpath="${dist_path}/${frame_dir}"
 
+	# The name of the sandbox directory.
+	sandbox_dir='sandbox'
+	sandbox_dirpath="${dist_path}/${sandbox_dir}"
+
 	# The name of the directory in which object files will be kept.
 	obj_dir='obj'
 	obj_dirpath="${cur_dirpath}/${obj_dir}"
@@ -1462,6 +1535,18 @@ main()
 
 	# The name of the directory in which the BLIS test suite is kept.
 	testsuite_dir='testsuite'
+
+	# -- Version-related --
+
+	# The shared library (.so) version file.
+	so_version_file='so_version'
+	so_version_filepath="${dist_path}/${so_version_file}"
+
+	# The major and minor/build .so version numbers.
+	so_version_major=''
+	so_version_minorbuild=''
+
+	# -- configure options --
 
 	# The user-given install prefix and a flag indicating it was given.
 	#install_prefix_def="${HOME}/blis"
@@ -1499,16 +1584,11 @@ main()
 	enable_memkind='' # The default memkind value is determined later on.
 	force_version='no'
 
-	# The shared library (.so) version file.
-	so_version_file='so_version'
-	so_version_filepath="${dist_path}/${so_version_file}"
+	# The sandbox flag and name.
+	sandbox_flag=''
+	sandbox=''
 
-	# The major and minor/build .so version numbers.
-	so_version_major=''
-	so_version_minorbuild=''
-
-	# Whether we are building out-of-tree.
-	configured_oot="no"
+	# -- Configuration registry --
 
 	# The name of the chosen configuration (the configuration "family").
 	config_name=''
@@ -1524,6 +1604,11 @@ main()
 	# in kernel_list.
 	kconfig_map=''
 
+	# -- Out-of-tree --
+
+	# Whether we are building out-of-tree.
+	configured_oot="no"
+
 	# Dummy file. Used to check whether the cwd is the same as the top-level
 	# source distribution directory.
 	dummy_file='_blis_dir_detect.tmp'
@@ -1532,7 +1617,7 @@ main()
 	# -- Command line option/argument parsing ----------------------------------
 
 	# Process our command line options.
-	while getopts ":hp:d:t:qci:b:-:" opt; do
+	while getopts ":hp:d:s:t:qci:b:-:" opt; do
 		case $opt in
 			-)
 				case "$OPTARG" in
@@ -1595,6 +1680,13 @@ main()
 					disable-packbuf-pools)
 						enable_packbuf_pools='no'
 						;;
+					enable-sandbox=*)
+						sandbox_flag=1
+						sandbox=${OPTARG#*=}
+						;;
+					disable-sandbox)
+						sandbox_flag=0
+						;;
 					int-size=*)
 						int_type_size=${OPTARG#*=}
 						;;
@@ -1640,6 +1732,10 @@ main()
 				debug_flag=1
 				debug_type=$OPTARG
 				;;
+			s)
+				sandbox_flag=1
+				sandbox=$OPTARG
+				;;
 			q)
 				quiet_flag=1
 				;;
@@ -1682,7 +1778,6 @@ main()
 		esac
 	done
 
-
 	# -- Check the operating system --------------------------------------------
 
 	os_name=$(uname -s)
@@ -1690,24 +1785,44 @@ main()
 	echo "${script_name}: detected ${os_name} kernel version ${os_vers}."
 
 
-	# -- Find a compiler -------------------------------------------------------
+	# -- Find a C compiler -----------------------------------------------------
 
 	# Acquire the compiler search order. This will vary based on the os
 	# found above.
 	cc_search_list=$(get_cc_search_list)
 
-	echo "${script_name}: compiler search list is: ${cc_search_list}."
+	echo "${script_name}: C compiler search list is: ${cc_search_list}."
 
 	# Find a working C compiler.
 	found_cc=$(select_cc "${cc_search_list}")
 
-	# If we didn't find any working compilers, we print an error message.
+	# If we didn't find any working C compilers, we print an error message.
 	if [ -z "${found_cc}" ]; then
-		echo "${script_name}: Could not find working compiler! Cannot continue."
+		echo "${script_name}: Could not find working C compiler! Cannot continue."
 		exit 1
 	fi
 
-	echo "${script_name}: using '${found_cc}' compiler."
+	echo "${script_name}: using '${found_cc}' C compiler."
+
+
+	# -- Find a C++ compiler ---------------------------------------------------
+
+	# Acquire the compiler search order. This will vary based on the os
+	# found above.
+	cxx_search_list=$(get_cxx_search_list)
+
+	echo "${script_name}: C++ compiler search list is: ${cxx_search_list}."
+
+	# Find a working C++ compiler.
+	found_cxx=$(select_cxx "${cxx_search_list}")
+
+	# If we didn't find any working C++ compilers, we print an error message.
+	if [ -z "${found_cxx}" ]; then
+		echo "${script_name}: Could not find working C++ compiler! Cannot continue."
+		exit 1
+	fi
+
+	echo "${script_name}: using '${found_cxx}' C++ compiler."
 
 
 	# -- Check the compiler version --------------------------------------------
@@ -2219,6 +2334,28 @@ main()
 		echo "${script_name}: the BLAS/CBLAS interface integer size is automatically determined."
 	fi
 
+	# Check if a sandbox was given.
+	if [ -n "${sandbox_flag}" ]; then
+
+		#sandbox_relpath="${sandbox_dir}/${sandbox}"
+
+		echo "${script_name}: configuring for alternate gemm implementation:"
+		echo "${script_name}:   ${sandbox_dir}/${sandbox}"
+
+		sandbox_fullpath="${sandbox_dirpath}/${sandbox}"
+
+		if [ ! -d "${sandbox_fullpath}" ]; then
+			echo "${script_name}: requested sandbox sub-directory does not exist! Cannot continue."
+			exit 1
+		fi
+
+		enable_sandbox_01=1
+	else
+		echo "${script_name}: configuring for conventional gemm implementation."
+
+		enable_sandbox_01=0
+	fi
+
 
 	# Variables that contain forward slashes, such as paths, need extra
 	# escaping when used in sed commands. We insert those extra escape
@@ -2227,6 +2364,11 @@ main()
 	install_incdir_esc=$(echo "${install_incdir}" | sed 's/\//\\\//g')
 	dist_path_esc=$(echo "${dist_path}"           | sed 's/\//\\\//g')
 	cc_esc=$(echo "${found_cc}" | sed 's/\//\\\//g')
+	cxx_esc=$(echo "${found_cxx}" | sed 's/\//\\\//g')
+	#sandbox_relpath_esc=$(echo "${sandbox_relpath}" | sed 's/\//\\\//g')
+
+	# For RANLIB, if the variable is not set, we use a default value of
+	# 'ranlib'.
 	ranlib_esc=$(echo "${RANLIB:-ranlib}" | sed 's/\//\\\//g')
 
 	# Create a #define for the configuration family (config_name).
@@ -2297,8 +2439,9 @@ main()
 		| sed -e "s/@kconfig_map@/${kconfig_map}/g" \
 		| sed -e "s/@os_name@/${os_name}/g" \
 		| sed -e "s/@dist_path@/${dist_path_esc}/g" \
-		| sed -e "s/@CC@/${cc_esc}/g" \
 		| sed -e "s/@CC_VENDOR@/${cc_vendor}/g" \
+		| sed -e "s/@CC@/${cc_esc}/g" \
+		| sed -e "s/@CXX@/${cxx_esc}/g" \
 		| sed -e "s/@RANLIB@/${ranlib_esc}/g" \
 		| sed -e "s/@debug_type@/${debug_type}/g" \
 		| sed -e "s/@threading_model@/${threading_model}/g" \
@@ -2311,6 +2454,7 @@ main()
 		| sed -e "s/@enable_blas@/${enable_blas}/g" \
 		| sed -e "s/@enable_cblas@/${enable_cblas}/g" \
 		| sed -e "s/@enable_memkind@/${enable_memkind}/g" \
+		| sed -e "s/@sandbox@/${sandbox}/g" \
 		> "${config_mk_out_path}"
 		
 
@@ -2332,6 +2476,7 @@ main()
 		| sed   -e "s/@enable_blas@/${enable_blas_01}/g" \
 		| sed   -e "s/@enable_cblas@/${enable_cblas_01}/g" \
 		| sed   -e "s/@enable_memkind@/${enable_memkind_01}/g" \
+		| sed   -e "s/@enable_sandbox@/${enable_sandbox_01}/g" \
 		> "${bli_config_h_out_path}"
 
 
@@ -2346,7 +2491,7 @@ main()
 
 	obj_config_dirpath="${base_obj_dirpath}/${config_dir}"
 
-	echo "${script_name}: creating ${obj_config_dirpath}"
+	#echo "${script_name}: creating ${obj_config_dirpath}"
 	mkdir -p ${obj_config_dirpath}
 	for conf in ${config_list}; do
 		echo "${script_name}: creating ${obj_config_dirpath}/${conf}"
@@ -2356,7 +2501,7 @@ main()
 
 	obj_kernels_dirpath="${base_obj_dirpath}/${kernels_dir}"
 
-	echo "${script_name}: creating ${obj_kernels_dirpath}"
+	#echo "${script_name}: creating ${obj_kernels_dirpath}"
 	mkdir -p ${obj_kernels_dirpath}
 	for kern in ${kernel_list}; do
 		echo "${script_name}: creating ${obj_kernels_dirpath}/${kern}"
@@ -2366,7 +2511,7 @@ main()
 
 	obj_refkern_dirpath="${base_obj_dirpath}/${refkern_dir}"
 
-	echo "${script_name}: creating ${obj_refkern_dirpath}"
+	#echo "${script_name}: creating ${obj_refkern_dirpath}"
 	mkdir -p ${obj_refkern_dirpath}
 	for conf in ${config_list}; do
 		echo "${script_name}: creating ${obj_refkern_dirpath}/${conf}"
@@ -2378,6 +2523,12 @@ main()
 
 	echo "${script_name}: creating ${obj_frame_dirpath}"
 	mkdir -p ${obj_frame_dirpath}
+
+
+	obj_sandbox_dirpath="${base_obj_dirpath}/${sandbox_dir}"
+
+	echo "${script_name}: creating ${obj_sandbox_dirpath}/${sandbox}"
+	mkdir -p ${obj_sandbox_dirpath}/${sandbox}
 
 
 	obj_blastest_dirpath="${base_obj_dirpath}/${blastest_dir}"
@@ -2444,6 +2595,10 @@ main()
 	# Mirror framework source tree to its object sub-directory.
 	echo "${script_name}: mirroring ${frame_dirpath} to ${obj_frame_dirpath}"
 	${mirror_tree_sh} ${frame_dirpath} ${obj_frame_dirpath}
+
+	# Mirror the chosen sandbox source tree to its object sub-directory.
+	echo "${script_name}: mirroring ${sandbox_dirpath}/${sandbox} to ${obj_sandbox_dirpath}/${sandbox}"
+	${mirror_tree_sh} "${sandbox_dirpath}/${sandbox}" "${obj_sandbox_dirpath}/${sandbox}"
 
 
 	# -- Generate makefile fragements ------------------------------------------
@@ -2515,6 +2670,17 @@ main()
 			 -o ${script_name} \
 			 -p 'FRAME' \
 			 ${frame_dirpath} \
+			 ${gen_make_frags_dirpath}/fragment.mk \
+			 ${gen_make_frags_dirpath}/suffix_list \
+			 ${gen_make_frags_dirpath}/ignore_list
+
+	# Generate makefile fragments in the sandbox sub-directory.
+	echo "${script_name}: creating makefile fragments in ${sandbox_dirpath}/${sandbox}"
+	${gen_make_frags_sh} \
+			 -h -r -v0 \
+			 -o ${script_name} \
+			 -p 'SANDBOX' \
+			 ${sandbox_dirpath}/${sandbox} \
 			 ${gen_make_frags_dirpath}/fragment.mk \
 			 ${gen_make_frags_dirpath}/suffix_list \
 			 ${gen_make_frags_dirpath}/ignore_list
