Add threading option to configure.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -88,6 +88,14 @@ print_usage()
 	echo "                 Enable (disabled by default) building BLIS as a shared"
 	echo "                 library. May be combined with --enable-static."
 	echo " "
+	echo "   -t MODEL, --enable-threading[=MODEL], --disable-threading"
+	echo " "
+	echo "                 Enable threading in the library, using threading model"
+	echo "                 MODEL={auto,omp,pthreads,no}. If MODEL=no or "
+	echo "                 --disable-threading is specified, threading will be"
+	echo "                 disabled. If MODEL=auto or is unspecified, a model"
+	echo "                 will be chosen automatically. The default is 'auto'."
+	echo " "
 	echo "   -q, --quiet   Suppress informational output. By default, configure"
 	echo "                 is verbose. (NOTE: -q is not yet implemented)"
 	echo " "
@@ -179,11 +187,14 @@ main()
 	debug_type=''
 	debug_flag=''
 
+	# The threading flag.
+	threading_model='auto'
+
 	# Option variables.
 	quiet_flag=''
 	
 	# Additional flags.
-	enable_verbose='yes'
+	enable_verbose='no'
 	enable_static='yes'
 	enable_shared='no'
 
@@ -210,7 +221,7 @@ main()
 
 
 	# Process our command line options.
-	while getopts ":hp:d:q-:" opt; do
+	while getopts ":hp:d:t:q-:" opt; do
 		case $opt in
 			-)
 				case "$OPTARG" in
@@ -232,6 +243,9 @@ main()
 						debug_flag=1
 						debug_type=${OPTARG#*=}
 						;;
+					disable-debug)
+						debug_flag=0
+						;;
 					enable-verbose-make)
 						enable_verbose='yes'
 						;;
@@ -250,6 +264,15 @@ main()
 					disable-shared)
 						enable_shared='no'
 						;;
+					enable-threading)
+						threading_model='auto'
+						;;
+					enable-threading=*)
+						threading_model=${OPTARG#*=}
+						;;
+					disable-threading)
+						threading_model='no'
+						;;
 					*)
 						print_usage
 						;;
@@ -267,6 +290,9 @@ main()
 				;;
 			q)
 				quiet_flag=1
+				;;
+			t)
+				threading_model=$OPTARG
 				;;
 			\?)
 				print_usage
@@ -376,6 +402,46 @@ main()
 		debug_type='off'
 		echo "${script_name}: debug symbols disabled."
 	fi
+
+
+	# Check if the verbose make flag was specified.
+	if [ "x${enable_verbose}" = "xyes" ]; then
+		echo "${script_name}: enabling verbose make output, disable with 'make V=0'."
+	else
+		echo "${script_name}: disabling verbose make output, enable with 'make V=1'."
+	fi
+
+
+	# Check if the static lib flag was specified.
+	if [ "x${enable_static}" = "xyes" ]; then
+		echo "${script_name}: building BLIS as a static library."
+	fi
+	
+	# Check if the shared lib flag was specified.
+	if [ "x${enable_shared}" = "xyes" ]; then
+		echo "${script_name}: building BLIS as a shared library."
+	fi
+	
+	# Check if neither flag was specified.
+	if [ "x${enable_static}" = "xno" -a "x${enable_shared}" = "xno" ]; then
+		echo "Neither a shared nor static library build has been requested."
+		exit 1
+	fi
+	
+	
+	# Check the threading model flag.
+	if [ "x${threading_model}" = "xauto" ]; then
+		echo "${script_name}: determining the threading model automatically."
+	elif [ "x${threading_model}" = "xomp" ]; then
+		echo "${script_name}: using OpenMP for threading."
+	elif [ "x${threading_model}" = "xpthreads" ]; then
+		echo "${script_name}: using Pthreads for threading."
+	elif [ "x${threading_model}" = "xno" ]; then
+		echo "${script_name}: threading is disabled."
+	else
+		echo "Unsupported threading model: ${threading_model}."
+		exit 1
+	fi
 	
 	
 	# Determine the compiler vendor if CC was specified.
@@ -389,7 +455,7 @@ main()
 			cc_vendor=`$CC -qversion 2>/dev/null | grep -o 'IBM'`
 		fi
 		if [ -z "$cc_vendor" ]; then
-			echo Unable to determine compiler vendor.
+			echo "Unable to determine compiler vendor."
 			exit 1
 		fi
 		cc_vendor=`echo $cc_vendor | { read first rest; echo $first; }`
@@ -416,7 +482,8 @@ main()
 		| sed "s/@install_prefix@/${install_prefix_esc}/g" \
 		| sed "s/@enable_verbose@/${enable_verbose}/g" \
 		| sed "s/@enable_static@/${enable_static}/g" \
-		| sed "s/@enable_shared@/${enable_shared}/g" \
+		| sed "s/@enable_dynamic@/${enable_shared}/g" \
+		| sed "s/@threading_model@/${threading_model}/g" \
 		> "${config_mk_out_path}"
 
 
